version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.7.7

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv ./virtualenvs/tap-zendesk
            . ./virtualenvs/tap-zendesk/bin/activate
            pip3 install --upgrade pip
            pip3 install -e .[test]

      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/tap-zendesk/bin/activate
            pylint --rcfile .pylintrc tap_zendesk/

      - run:
          name: 'Unit Tests'
          command: |
            . ./virtualenvs/tap-zendesk/bin/activate
            export LOGGING_CONF_FILE=./sample_logging.conf
            nosetests -c .noserc test
workflows:
  version: 2
  build:
    jobs:
      - build
